// <auto-generated />
using BooksShopWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksShopWeb.Migrations;

[DbContext(typeof(ApplicationDBContext))]
[Migration("20260912144621_AddDisplayOrderColumntoCategoriesTable")]
partial class _20260912144621_AddDisplayOrderColumntoCategoriesTable
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("BooksShopWeb.Models.Category", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<int>("DisplayOrder")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Categories");

                b.HasData(
                    new
                    {
                        Id = 1,
                        DisplayOrder = 1,
                        Name = "Action"
                    },
                    new
                    {
                        Id = 2,
                        DisplayOrder = 2,
                        Name = "Biography"
                    },
                    new
                    {
                        Id = 3,
                        DisplayOrder = 3,
                        Name = "Children"
                    },
                    new
                    {
                        Id = 4,
                        DisplayOrder = 4,
                        Name = "Crime"
                    },
                    new
                    {
                        Id = 5,
                        DisplayOrder = 5,
                        Name = "Fantasy"
                    });
            });
#pragma warning restore 612, 618
    }
}
